### ISSUE TITLE
Need to fix startup page

### ISSUE THREAD

**Issue by cganesh8** [Subra730/Spider#5]
@Subra730, 

When you moved to the components model, the startup page contents got moved into components/home.

Now we have a startup page that is blank, top half has black background, bottom half white.

Any thoughts on how we should fix this.
![Screenshot (3)](https://user-images.githubusercontent.com/31004134/82522281-471bd100-9b6c-11ea-8b1e-b033aaaa764c.png)

**Comment by Subra730** [comment]
@cganesh8, Startup Page Issue fixed. 
![Screenshot (1)](https://user-images.githubusercontent.com/62677682/82525983-1476d600-9b76-11ea-95f3-85d2283b5345.png)
